
import { User, Role, Lawyer, Booking, BookingStatus, Language } from './types';

export const MOCK_USERS: User[] = [
  { id: 'user1', name: 'Aarav Sharma', email: 'user@example.com', phone: '9876543210', role: Role.USER },
  { id: 'lawyer1', name: 'Adv. Priya Singh', email: 'lawyer@example.com', phone: '8765432109', role: Role.LAWYER },
  { id: 'admin1', name: 'Admin', email: 'admin@example.com', phone: '7654321098', role: Role.ADMIN },
];

export const MOCK_LAWYERS: Lawyer[] = [
  {
    id: 'lawyer1',
    name: 'Adv. Priya Singh',
    photo: 'https://picsum.photos/seed/priya/200',
    fees: 2500,
    services: ['Property Registration', 'Contract Law', 'Notary'],
    experience: 8,
    rating: 4.8,
    reviews: 124,
    location: { lat: 19.0760, lng: 72.8777, address: 'Andheri, Mumbai' },
    isVerified: true,
    contactUnlocked: false,
    pan: 'ABCDE1234F',
    aadhar: '1234 5678 9012',
    barId: 'MAH/1234/2015',
    availability: {
      '2024-08-15': ['10:00', '11:00', '14:00', '15:00'],
      '2024-08-16': ['09:00', '10:00', '11:00', '12:00'],
    }
  },
  {
    id: 'lawyer2',
    name: 'Adv. Rohan Gupta',
    photo: 'https://picsum.photos/seed/rohan/200',
    fees: 3000,
    services: ['Real Estate Law', 'Document Verification'],
    experience: 12,
    rating: 4.9,
    reviews: 210,
    location: { lat: 19.0213, lng: 72.8424, address: 'Dadar, Mumbai' },
    isVerified: true,
    contactUnlocked: false,
    pan: 'FGHIJ5678K',
    aadhar: '2345 6789 0123',
    barId: 'MAH/5678/2011',
    availability: {
      '2024-08-15': ['13:00', '14:00', '16:00'],
      '2024-08-17': ['10:00', '11:00', '15:00', '16:00'],
    }
  },
  {
    id: 'lawyer3',
    name: 'Adv. Anjali Desai',
    photo: 'https://picsum.photos/seed/anjali/200',
    fees: 2000,
    services: ['Contract Drafting', 'Legal Consultation'],
    experience: 5,
    rating: 4.7,
    reviews: 89,
    location: { lat: 19.1136, lng: 72.8697, address: 'Goregaon, Mumbai' },
    isVerified: false,
    contactUnlocked: false,
    pan: 'KLMNO9012L',
    aadhar: '3456 7890 1234',
    barId: 'MAH/9012/2018',
    availability: {
      '2024-08-16': ['10:00', '11:00', '14:00'],
      '2024-08-18': ['09:00', '12:00', '13:00'],
    }
  },
];

export const MOCK_BOOKINGS: Booking[] = [
    {
        id: 'booking1',
        userId: 'user1',
        lawyerId: 'lawyer1',
        userName: 'Aarav Sharma',
        lawyerName: 'Adv. Priya Singh',
        date: '2024-08-15',
        time: '10:00',
        status: BookingStatus.CONFIRMED,
        documents: [],
        payment: { amount: 2500, status: 'Paid', method: 'UPI', transactionId: 'TXN123456' }
    },
    {
        id: 'booking2',
        userId: 'user1',
        lawyerId: 'lawyer2',
        userName: 'Aarav Sharma',
        lawyerName: 'Adv. Rohan Gupta',
        date: '2024-08-17',
        time: '11:00',
        status: BookingStatus.PENDING,
        documents: [],
        payment: { amount: 3000, status: 'Unpaid', method: 'Card', transactionId: '' }
    }
];

export const UNLOCK_FEE = 99;
export const PLATFORM_COMMISSION = 0.15; // 15%

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: 'LegalConnect',
    loginTitle: 'Welcome to LegalConnect',
    loginSubtitle: 'Find and book verified lawyers near you.',
    emailLabel: 'Email',
    loginButton: 'Login',
    userLogin: 'Login as User',
    lawyerLogin: 'Login as Lawyer',
    adminLogin: 'Login as Admin',
    findLawyers: 'Find Lawyers Near Me',
    mapView: 'Map View',
    listView: 'List View',
    verified: 'Verified',
    experience: 'Yrs Exp',
    reviews: 'Reviews',
    viewProfile: 'View Profile',
    unlockContact: `Unlock Contact for ₹${UNLOCK_FEE}`,
    bookAppointment: 'Book Appointment',
    selectDate: 'Select a Date',
    selectTime: 'Select a Time',
    uploadDocs: 'Upload Documents (PDF, JPG)',
    confirmBooking: 'Confirm Booking',
    myBookings: 'My Bookings',
    status: 'Status',
    lawyerDashboard: 'Lawyer Dashboard',
    bookingRequests: 'Booking Requests',
    confirm: 'Confirm',
    reject: 'Reject',
    availability: 'My Availability',
    earnings: 'My Earnings',
    totalEarnings: 'Total Earnings',
    platformFee: 'Platform Fee',
    netPayout: 'Net Payout',
    adminDashboard: 'Admin Dashboard',
    lawyerVerification: 'Lawyer Verification',
    approve: 'Approve',
    settings: 'Settings',
    unlockFee: 'Unlock Fee',
    commissionRate: 'Commission Rate',
    update: 'Update',
    analytics: 'Analytics',
    totalRevenue: 'Total Revenue',
    totalBookings: 'Total Bookings',
    activeLawyers: 'Active Lawyers',
    logout: 'Logout',
    language: 'Language',
    services: 'Services',
    contact: 'Contact Details',
    callNow: 'Call Now',
    message: 'Message',
    documentSummary: 'Get AI Document Summary',
    summarizing: 'Summarizing...',
    summaryError: 'Failed to get summary.',
    summaryTitle: 'AI Document Analysis',
    summaryPoints: 'Summary Points',
    potentialIssues: 'Potential Issues',
    recommendations: 'Recommendations',
  },
  [Language.MR]: {
    appName: 'लीगलकनेक्ट',
    loginTitle: 'लीगलकनेक्ट मध्ये आपले स्वागत आहे',
    loginSubtitle: 'तुमच्या जवळ सत्यापित वकील शोधा आणि बुक करा.',
    emailLabel: 'ईमेल',
    loginButton: 'लॉगिन करा',
    userLogin: 'वापरकर्ता म्हणून लॉगिन करा',
    lawyerLogin: 'वकील म्हणून लॉगिन करा',
    adminLogin: 'प्रशासक म्हणून लॉगिन करा',
    findLawyers: 'माझ्या जवळ वकील शोधा',
    mapView: ' नकाशा दृश्य',
    listView: 'सूची दृश्य',
    verified: 'सत्यापित',
    experience: 'वर्षे अनुभव',
    reviews: 'पुनरावलोकने',
    viewProfile: 'प्रोफाइल पहा',
    unlockContact: `संपर्क ₹${UNLOCK_FEE} मध्ये अनलॉक करा`,
    bookAppointment: 'अपॉइंटमेंट बुक करा',
    selectDate: 'एक तारीख निवडा',
    selectTime: 'एक वेळ निवडा',
    uploadDocs: 'दस्तऐवज अपलोड करा (PDF, JPG)',
    confirmBooking: 'बुकिंगची पुष्टी करा',
    myBookings: 'माझी बुकिंग',
    status: 'स्थिती',
    lawyerDashboard: 'वकील डॅशबोर्ड',
    bookingRequests: 'बुकिंग विनंत्या',
    confirm: 'पुष्टी करा',
    reject: 'नकार द्या',
    availability: 'माझी उपलब्धता',
    earnings: 'माझी कमाई',
    totalEarnings: 'एकूण कमाई',
    platformFee: 'प्लॅटफॉर्म शुल्क',
    netPayout: 'निव्वळ पेमेंट',
    adminDashboard: 'प्रशासक डॅशबोर्ड',
    lawyerVerification: 'वकील पडताळणी',
    approve: 'मंजूर करा',
    settings: 'सेटिंग्ज',
    unlockFee: 'अनलॉक शुल्क',
    commissionRate: 'कमिशन दर',
    update: 'अपडेट करा',
    analytics: 'विश्लेषण',
    totalRevenue: 'एकूण महसूल',
    totalBookings: 'एकूण बुकिंग',
    activeLawyers: 'सक्रिय वकील',
    logout: 'लॉगआउट',
    language: 'भाषा',
    services: 'सेवा',
    contact: 'संपर्क तपशील',
    callNow: 'आता कॉल करा',
    message: 'संदेश',
    documentSummary: 'AI दस्तऐवज सारांश मिळवा',
    summarizing: 'सारांशित करत आहे...',
    summaryError: 'सारांश मिळविण्यात अयशस्वी.',
    summaryTitle: 'AI दस्तऐवज विश्लेषण',
    summaryPoints: 'सारांश मुद्दे',
    potentialIssues: 'संभाव्य समस्या',
    recommendations: 'शिफारसी',
  },
};
